[build]
publish = "public"
command = "gatsby build"

[[redirects]]
from = "/1"
to = "/posts/Episode-1/"
status = 301
force = true

[[redirects]]
from = "/players"
to = "https://bit.ly/IDPGPlayers"
status = 301
force = true

[[redirects]]
from = "/subscribe"
to = "http://eepurl.com/hfXWCf"
status = 301
force = true

[[redirects]]
from = "/discord"
to = "https://discord.gg/mk7gnfB"
status = 301
force = true
