[build]
publish = "public"
command = "gatsby build"

[[redirects]]
from = "/1"
to = "/posts/Episode-1/"
status = 301
force = true

[[redirects]]
from = "/players"
to = "https://bit.ly/IDPGPlayers"
status = 301
force = true
