[build]
publish = "public"
command = "gatsby clean && gatsby build"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

[[redirects]]
from = "/players"
to = "/player-info/"
status = 301
force = true

[[redirects]]
from = "/subscribe"
to = "http://eepurl.com/hfXWCf"
status = 301
force = true

[[redirects]]
from = "/discord"
to = "https://discord.gg/c8cHAWm"
status = 301
force = true

[[redirects]]
from = "/calendar"
to = "https://calendar.google.com/calendar/u/0?cid=Y181ajAxY3ZjNnA5YWwyaHVmdDFkdnNsYWF1OEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t"
status = 301
force = true

[[redirects]]
from = "/store"
to = "https://teespring.com/stores/devopspartygames"
status = 301
force = true

[[redirects]]
from = "/suggest-player"
to = "https://airtable.com/shrdoxisE5VQpsnGs"
status = 301
force = true

[[redirects]]
from = "/suggestplayer"
to = "https://airtable.com/shrdoxisE5VQpsnGs"
status = 301
force = true

[[redirects]]
from = "/suggest-prompt"
to = "https://airtable.com/shrPE2retwrKcgk62"
status = 301
force = true

[[redirects]]
from = "/suggestprompt"
to = "https://airtable.com/shrPE2retwrKcgk62"
status = 301
force = true
